package jpeg2000

import (
	"bytes"
	"fmt"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"testing"
)

// loadRef loads the PNG reference decode generated by testdata/gen.py.
func loadRef(t *testing.T, name string) image.Image {
	t.Helper()
	f, err := os.Open(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("reference image: %v", err)
	}
	defer f.Close()
	img, err := png.Decode(f)
	if err != nil {
		t.Fatalf("decoding reference: %v", err)
	}
	return img
}

func decodeFile(t *testing.T, name string) image.Image {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("reading %s: %v", name, err)
	}
	img, err := Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("decoding %s: %v", name, err)
	}
	return img
}

// compare returns the maximum per-channel absolute difference and the
// mean absolute difference between two images.
func compare(t *testing.T, got, want image.Image) (int, float64) {
	t.Helper()
	gb, wb := got.Bounds(), want.Bounds()
	if gb.Dx() != wb.Dx() || gb.Dy() != wb.Dy() {
		t.Fatalf("size mismatch: got %v, want %v", gb, wb)
	}
	maxDiff := 0
	var sum, n float64
	for y := 0; y < gb.Dy(); y++ {
		for x := 0; x < gb.Dx(); x++ {
			gr, gg, gbl, ga := got.At(gb.Min.X+x, gb.Min.Y+y).RGBA()
			wr, wg, wbl, wa := want.At(wb.Min.X+x, wb.Min.Y+y).RGBA()
			for _, d := range [4]int{
				absInt(int(gr>>8) - int(wr>>8)),
				absInt(int(gg>>8) - int(wg>>8)),
				absInt(int(gbl>>8) - int(wbl>>8)),
				absInt(int(ga>>8) - int(wa>>8)),
			} {
				maxDiff = max(maxDiff, d)
				sum += float64(d)
				n++
			}
		}
	}
	return maxDiff, sum / n
}

func absInt(v int) int {
	if v < 0 {
		return -v
	}
	return v
}

func testAgainstRef(t *testing.T, file string, maxTol int, meanTol float64) {
	got := decodeFile(t, file)
	want := loadRef(t, file[:len(file)-len(filepath.Ext(file))]+".png")
	maxDiff, meanDiff := compare(t, got, want)
	if maxDiff > maxTol || meanDiff > meanTol {
		t.Errorf("%s: max diff %d (tol %d), mean diff %.3f (tol %.3f)",
			file, maxDiff, maxTol, meanDiff, meanTol)
	}
}

func TestLossless(t *testing.T) {
	for _, file := range []string{
		"rgb_lossless.j2k",
		"rgb_lossless.jp2",
		"gray_lossless.j2k",
		"rgb_tiled.j2k",
		"tiny_3x5.j2k",
		"tiny_1x7.j2k",
		"rgb_cb32.j2k",
		"rgb_precincts.j2k",
		"rgb_res3.j2k",
		"rgb_rlcp.j2k",
		"rgb_rpcl.j2k",
		"rgb_pcrl.j2k",
		"rgb_cprl.j2k",
		"rgb_nomct.j2k",
		"rgba_lossless.jp2",
	} {
		t.Run(file, func(t *testing.T) {
			testAgainstRef(t, file, 0, 0) // lossless must be bit-exact
		})
	}
}

func TestLossy(t *testing.T) {
	for _, file := range []string{
		"rgb_lossy.j2k",
		"gray_lossy.j2k",
		"rgb_layers.j2k",
	} {
		t.Run(file, func(t *testing.T) {
			// Small differences from the reference decoder are
			// acceptable: float rounding in the 9/7 filter differs
			// between implementations.
			testAgainstRef(t, file, 2, 0.01)
		})
	}
}

func TestDecodeConfig(t *testing.T) {
	for _, tc := range []struct {
		file string
		w, h int
	}{
		{"rgb_lossless.j2k", 97, 61},
		{"rgb_lossless.jp2", 97, 61},
		{"rgba_lossless.jp2", 64, 48},
	} {
		data, err := os.ReadFile(filepath.Join("testdata", tc.file))
		if err != nil {
			t.Fatal(err)
		}
		cfg, err := DecodeConfig(bytes.NewReader(data))
		if err != nil {
			t.Fatalf("%s: %v", tc.file, err)
		}
		if cfg.Width != tc.w || cfg.Height != tc.h {
			t.Errorf("%s: got %dx%d, want %dx%d",
				tc.file, cfg.Width, cfg.Height, tc.w, tc.h)
		}
	}
}

func TestImageDecodeRegistration(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "rgb_lossless.jp2"))
	if err != nil {
		t.Fatal(err)
	}
	img, format, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	if format != "jp2" {
		t.Errorf("format = %q, want jp2", format)
	}
	if img.Bounds().Dx() != 97 {
		t.Errorf("width = %d, want 97", img.Bounds().Dx())
	}
}

func TestInvalidInput(t *testing.T) {
	for _, data := range [][]byte{
		nil,
		[]byte("not a jpeg2000 file"),
		{0xFF, 0x4F},
		bytes.Repeat([]byte{0xFF, 0x4F, 0xFF, 0x51}, 3),
	} {
		if _, err := Decode(bytes.NewReader(data)); err == nil {
			t.Errorf("Decode(%x) succeeded, want error", data)
		}
	}
}

func FuzzDecode(f *testing.F) {
	seeds, _ := filepath.Glob(filepath.Join("testdata", "*.j2k"))
	for _, s := range seeds {
		if data, err := os.ReadFile(s); err == nil {
			f.Add(data)
		}
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		img, err := Decode(bytes.NewReader(data))
		if err == nil && img != nil {
			b := img.Bounds()
			_ = fmt.Sprintf("%v", b)
		}
	})
}
